# Generated by Django 3.2.6 on 2021-10-21 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ae_token',
            field=models.TextField(default=''),
        ),
    ]
