# Generated by Django 3.2.6 on 2021-11-03 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_ae_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ae_token',
            field=models.TextField(blank=True, default=''),
        ),
    ]
