# Generated by Django 3.2.6 on 2021-12-21 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ae_id',
            field=models.CharField(blank='', default='', help_text='This is used to link AE accounts to your account', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ae_token',
            field=models.TextField(blank=True, default='', editable=False),
        ),
    ]
