# Generated by Django 3.2.6 on 2021-12-21 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('check_in', '0002_remove_student_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the school', max_length=100)),
                ('ae_subdomain', models.CharField(blank=True, default='', help_text="Enter the subdomain of the accelerate ed site. Ex: 'hogwarts.agilixbuzz.com' would be 'hogwarts'.", max_length=200)),
                ('ae_domainid', models.CharField(blank='', default='', help_text='This value is used to make API calls to accelerate ed. Leave blank if your not sure.', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='ae_id',
            field=models.CharField(blank=True, default='', help_text='This value is used to link AE course to the app.', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='ae_id',
            field=models.CharField(blank=True, default='', help_text='This value is used to link AE accounts to students.', max_length=20),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='school',
            field=models.ForeignKey(blank=True, help_text='Select school providing course.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='check_in.school'),
        ),
    ]
